---
- name: Issue SSL certificate for containerized AAP
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Issue Let's Encrypt certificate for AAP
      ansible.builtin.include_role:
        name: issue_cert_containerized
      vars:
        # Required: Your DNS name
        dns_name: "aap-nostromo.demoredhat.com"

        # Optional: Customize ports (defaults shown)
        # nginx_frontend_port: 8444     # Port where nginx will listen with valid cert
        # aap_backend_port: 443         # Port where AAP is currently running

        # Optional: Customize email for Let's Encrypt
        # letsencrypt_email: "your-email@example.com"

        # Note: Users will access AAP at https://aap-nostromo.demoredhat.com:8444
        # with a valid Let's Encrypt SSL certificate
