---
- name: Issue SSL certificate for containerized AAP
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Issue certificate with envoy modification
      ansible.builtin.include_role:
        name: issue_cert_containerized
      vars:
        # Required: Your DNS name
        dns_name: "aap-nostromo.demoredhat.com"

        # IMPORTANT: Set to true to move AAP from 443 to 8501
        # This allows nginx to take over port 443
        modify_envoy: true

        # Optional: Customize ports (defaults shown)
        # nginx_frontend_port: 443      # Port where nginx will listen
        # aap_backend_port: 8501        # Port where AAP will be moved to

        # Optional: Customize email for Let's Encrypt
        # letsencrypt_email: "your-email@example.com"
